import os
import datetime
from bson import ObjectId
from pydantic import BaseModel
from fastapi import APIRouter, HTTPException, BackgroundTasks
from database import get_database
from services.auth_service import hash_password

router = APIRouter(prefix="/setup", tags=["setup"])

class SetupRequest(BaseModel):
    mongoUri: str
    chromaUri: str
    aiProvider: str
    aiKey: str
    dlpProxyUrl: str
    adminName: str
    adminEmail: str
    adminPassword: str

@router.get("/status")
async def check_setup_status():
    try:
        user_count = await get_database()["users"].count_documents({"role": "admin"})
        return {"is_configured": user_count > 0, "needs_wizard": user_count == 0}
    except Exception as e:
        return {"is_configured": False, "needs_wizard": True, "error": str(e)}

@router.post("/run")
async def run_setup(req: SetupRequest, background_tasks: BackgroundTasks):
    db = get_database()
    if (await check_setup_status()).get("is_configured"):
        raise HTTPException(status_code=403, detail="Sistema já configurado.")

    ws_result = await db["workspaces"].insert_one({
        "workspace_name": "Matriz / General",
        "document": "SETUP_WIZARD",
        "admin_email": req.adminEmail,
        "onboarding_completed": True,
        "created_at": datetime.datetime.utcnow(),
    })

    await db["users"].insert_one({
        "name": req.adminName,
        "email": req.adminEmail,
        "hashed_password": hash_password(req.adminPassword),
        "role": "admin",
        "workspace_id": str(ws_result.inserted_id),
        "is_active": True,
        "created_at": datetime.datetime.utcnow(),
    })

    # Escreve o .env na Host OS
    env_content = f\"\"\"# THEMIS ENV GENERATED BY WIZARD
MONGODB_URL={req.mongoUri}
CHROMA_URL={req.chromaUri}
GEMINI_API_KEY={req.aiKey}
VETTA_SHIELD_PROXY={req.dlpProxyUrl}
JWT_SECRET=themis_super_secure_secret_{os.urandom(16).hex()}
ENCRYPTION_KEY={os.urandom(32).hex()}
\"\"\"
    
    try:    
        with open(".env", "w") as f:
            f.write(env_content)
    except IOError:
        pass # Handle permissions in strict docker OS

    return {"message": "Setup de elite finalizado com sucesso. Reinicie seu backend."}
